apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-from-dockerfile
spec:
  params:
  - default: "true"
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS
      registry)
    name: TLSVERIFY
    type: string
  - default: ./Dockerfile
    description: Path to the Dockerfile file
    name: DOCKERFILE_PATH
    type: string
  - default: latest
    description: Tag for the built image
    name: IMAGE_TAG
    type: string
  resources:
    inputs:
    - name: source
      type: git
    outputs:
    - name: image
      type: image
  steps:
  - command:
    - buildah
    - bud
    - --tls-verify=$(inputs.params.TLSVERIFY)
    - --layers
    - -f
    - $(inputs.params.DOCKERFILE_PATH)
    - -t
    - $(outputs.resources.image.url):$(inputs.params.IMAGE_TAG)
    - .
    image: quay.io/buildah/stable
    name: build
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: /workspace/source
  - command:
    - buildah
    - push
    - --tls-verify=$(inputs.params.TLSVERIFY)
    - $(outputs.resources.image.url):$(inputs.params.IMAGE_TAG)
    - docker://$(outputs.resources.image.url):$(inputs.params.IMAGE_TAG)
    image: quay.io/buildah/stable
    name: push
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers