apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: camel-quarkus-quickstart-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/camel-quarkus-quickstart-ci/camel-quarkus-quickstart
