apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-pipeline
spec:
  params:
  - name: mavenMirrorUrl
    type: string
    default: https://repo1.maven.org/maven2
    description: The Maven Mirror URL to use for
  - name: mavenCmdArgs
    type: string
    default: clean -DskipTests package
    description: The maven goals to pass to the build
  - name: runScript
    type: string
    default: /usr/local/bin/maven-run.sh
    description: The buildah script to run
  resources:
  - name: source-repo
    type: git
  tasks:
  - name: maven-build
    taskRef:
      kind: Task
      name: maven-build
    params:
    - name: mavenMirrorUrl
      value: $(params.mavenMirrorUrl)
    - name: mavenCmdArgs
      value: $(params.mavenCmdArgs)
    - name: runScript
      value: $(params.runScript)
    resources:
      inputs:
      - name: git-source
        resource: source-repo