apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: java-native-build
spec:
  params:
  - name: PATH_CONTEXT
    type: string
    default: /workspace/git-source
    description: The Maven build context dir
  - name: MAVEN_MIRROR_URL
    type: string
    default: https://repo1.maven.org/maven2
    description: The MAVEN_MIRROR_URL url to use
  - name: MAVEN_CMD_ARGS
    type: string
    default: clean -DskipTests install -Pnative
    description: The maven command parameter
  - name: RUN_SCRIPT
    type: string
    default: /usr/local/bin/maven-run.sh
    description: The script to use during
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - name: maven-build
    image: quay.io/rhdevelopers/quarkus-java-builder
    args:
    - $(params.RUN_SCRIPT)
    env:
    - name: WORK_DIR
      value: $(params.PATH_CONTEXT)
    - name: MAVEN_MIRROR_URL
      value: $(params.MAVEN_MIRROR_URL)
    - name: MVN_CMD_ARGS
      value: $(params.MAVEN_CMD_ARGS)
    resources: {}
    volumeMounts:
    - mountPath: /root/.m2
      name: m2-cache
  volumes:
  - name: m2-cache
    persistentVolumeClaim:
      claimName: m2-cache
