apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jvm-build-task
spec:
  params:
  - name: contextDir
    type: string
    default: /workspace/git-source
    description: The Docker build context Dir
  - name: mavenMirrorUrl
    type: string
    default: https://repo1.maven.org/maven2
    description: The MAVEN_MIRROR_URL url to use
  - name: mavenCmdArgs
    type: string
    default: clean -DskipTests install -Pnative
    description: The maven command parameter
  - name: runScript
    type: string
    default: /usr/local/bin/maven-run.sh
    description: The script to use during
  - name: push
    type: string
    default: "true"
    description: Whether to push the image to container registry or not
  resources:
    inputs:
    - name: git-source
      type: git
    outputs:
    - name: builtImage
      type: image
  steps:
  - name: buildah-build-push
    image: quay.io/rhdevelopers/quarkus-java-builder
    imagePullPolicy: IfNotPresent
    args:
    - $(params.runScript)
    env:
    - name: MAVEN_MIRROR_URL
      value: $(params.mavenMirrorUrl)
    - name: WORK_DIR
      value: $(params.contextDir)
    - name: PUSH
      value: $(params.push)
    - name: MVN_CMD_ARGS
      value: $(params.mavenCmdArgs)
    - name: DESTINATION_NAME
      value: $(resources.outputs.builtImage.url)
    resources: {}
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    volumeMounts:
    - mountPath: /root/.m2
      name: m2-cache
  volumes:
  - name: m2-cache
    persistentVolumeClaim:
      claimName: m2-cache
