apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: java-pipeline-run
spec:
  pipelineRef:
    name: java-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: camel-quarkus-quickstart-git