apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:
  params:
  - name: mavenMirrorUrl
    type: string
    default: https://repo1.maven.org/maven2
    description: The MAVEN_MIRROR_URL url to use
  - name: mavenCmdArgs
    type: string
    default: clean -DskipTests install -Pnative
    description: The maven command parameter
  - name: runScript
    type: string
    default: /usr/local/bin/maven-run.sh
    description: The script to use during
  resources:
    inputs:
    - name: git-source
      type: git
  steps:
  - name: maven-build
    image: quay.io/rhdevelopers/quarkus-java-builder
    imagePullPolicy: IfNotPresent
    args:
    - $(params.runScript)
    env:
    - name: MAVEN_MIRROR_URL
      value: $(params.mavenMirrorUrl)
    - name: MVN_CMD_ARGS
      value: $(params.mavenCmdArgs)
    resources: {}
    volumeMounts:
    - mountPath: /root/.m2
      name: m2-cache
  volumes:
  - name: m2-cache
    persistentVolumeClaim:
      claimName: m2-cache
