apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: s2i-java-11-maven
spec:
  params:
  - name: PATH_CONTEXT
    type: string
    default: .
    description: The location of the path to run s2i from
  - name: TLSVERIFY
    type: string
    default: "true"
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
  - name: MAVEN_ARGS_APPEND
    type: string
    default: ""
    description: Additional Maven arguments
  - name: MAVEN_CLEAR_REPO
    type: string
    default: "false"
    description: Remove the Maven repository after the artifact is built
  - name: MAVEN_MIRROR_URL
    type: string
    default: ""
    description: The base URL of a mirror used for retrieving artifacts
  resources:
    inputs:
    - name: source
      type: git
    outputs:
    - name: image
      type: image
  steps:
  - name: gen-env-file
    image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
    args:
    - |-
      echo "MAVEN_CLEAR_REPO=$(params.MAVEN_CLEAR_REPO)" > env-file

      [[ '$(params.MAVEN_ARGS_APPEND)' != "" ]] &&
        echo "MAVEN_ARGS_APPEND=$(params.MAVEN_ARGS_APPEND)" >> env-file

      [[ '$(params.MAVEN_MIRROR_URL)' != "" ]] &&
        echo "MAVEN_MIRROR_URL=$(params.MAVEN_MIRROR_URL)" >> env-file

      echo "Generated Env file"
      echo "------------------------------"
      cat env-file
      echo "------------------------------"
    command:
    - /bin/sh
    - -c
    resources: {}
    volumeMounts:
    - mountPath: /env-params
      name: envparams
    workingDir: /env-params
  - name: generate
    image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
    command:
    - s2i
    - build
    - $(params.PATH_CONTEXT)
    - registry.access.redhat.com/openjdk/openjdk-11-rhel7
    - --image-scripts-url
    - image:///usr/local/s2i
    - --as-dockerfile
    - /gen-source/Dockerfile.gen
    - --environment-file
    - /env-params/env-file
    resources: {}
    volumeMounts:
    - mountPath: /gen-source
      name: gen-source
    - mountPath: /env-params
      name: envparams
    workingDir: /workspace/source
  - name: build
    image: registry.redhat.io/rhel8/buildah
    command:
    - buildah
    - bud
    - --tls-verify=$(params.TLSVERIFY)
    - --layers
    - -f
    - /gen-source/Dockerfile.gen
    - -t
    - $(resources.outputs.image.url)
    - .
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    - mountPath: /gen-source
      name: gen-source
    workingDir: /gen-source
  - name: push
    image: registry.redhat.io/rhel8/buildah
    command:
    - buildah
    - push
    - --tls-verify=$(params.TLSVERIFY)
    - $(resources.outputs.image.url)
    - docker://$(resources.outputs.image.url)
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
  - emptyDir: {}
    name: gen-source
  - emptyDir: {}
    name: envparams