apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: camel-quarkus-quickstart-build-pipeline
spec:
  params:
  - default: latest
    description: Tag for the built image
    name: imageTag
    type: string
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build-and-push
    params:
    - name: DOCKERFILE_PATH
      value: ./Dockerfile
    - name: IMAGE_TAG
      value: $(params.imageTag)
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
    taskRef:
      kind: Task
      name: build-from-dockerfile
