apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: camel-quarkus-quickstart
spec:
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/camel-quarkus-quickstart-ci/camel-quarkus-quickstart:latest
        livenessProbe:
          httpGet:
            path: /health/live
        readinessProbe:
          httpGet:
            path: /health/ready
