---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: argocd
spec:
  targetNamespaces:
  - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
spec:
  channel: alpha
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace